
version: 0.0
os: linux
files:
  - source: target/ROOT.war
    destination: /opt/apache-tomcat-9.0.4/webapps
permissions:
  - object: /opt/apache-tomcat-9.0.4/webapps
    pattern: "*.war"
    owner: tomcat
    group: tomcat
    mode: 664
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/RemoveTomcatRoot
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/RestartService
      timeout: 300
      runas: root
