
version: 0.0
os: linux
files:
  - source: target/ROOT.war
    destination: /opt/apache-tomcat-9.0.4/webapps
permissions:
  - object: /opt/apache-tomcat-9.0.4/webapps
    pattern: "*.war"
    owner: tomcat
    group: tomcat
    mode: 664
    type:
      - file
hooks:
  ApplicationStop:
    - location: scripts/StopService
      timeout: 3600
      runas: root
  BeforeInstall:
    - location: scripts/RemoveAppRoot
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/StartService
      timeout: 3600
      runas: root
  ValidateService:
    - location: scripts/ValidateService
      timeout: 3600
      runas: root
