
version: 0.0
os: linux
files:
  - source: target/app.war
    destination: /opt/apache-tomcat-9.0.4/webapps/ROOT.war
permissions:
  - object: /opt/apache-tomcat-9.0.4/webapps/
    pattern: "**"
    owner: tomcat
    group: tomcat
    mode: 755
    type:
      - directory
hooks:
  BeforeInstall:
    - location: scripts/RemoveTomcatRoot
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/RestartService
      timeout: 300
      runas: root
