
version: 0.0
os: linux
files:
  - source: target/app.war
    destination: /opt/apache-tomcat-9.0.4/webapps/ROOT.war
permissions:
  - object: /opt/apache-tomcat-9.0.4/webapps/ROOT.war
    owner: tomcat
    group: tomcat
    mode: 664
hooks:
  BeforeInstall:
    - location: scripts/RemoveTomcatRoot
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/RestartService
      timeout: 300
      runas: ec2-user
